collections:
  authors:
    output: true

remote_theme: just-the-docs/just-the-docs

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

aux_links:
  "Github":
    - "//github.com/hyperswine/Neutron"

footer_content: "Neutron<sup>TM</sup>"

color_scheme: great

plugins:
  - jekyll-feed
